export enum Role {
  ADM = 'ADM',
  TEC = 'TEC',
  USR = 'USR'
}

export enum TicketEstado {
  PENDIENTE = 'PENDIENTE',
  ASIGNADO = 'ASIGNADO',
  EN_PROCESO = 'EN_PROCESO',
  ESPERA_CLIENTE = 'ESPERA_CLIENTE',
  RESUELTO = 'RESUELTO',
  CERRADO = 'CERRADO',
  CANCELADO = 'CANCELADO'
}

export enum ModoAsignacion {
  AUTOMATICA = 'AUTOMATICA',
  MANUAL = 'MANUAL'
}

export enum Prioridad {
  BAJO = 'BAJO',
  MEDIO = 'MEDIO',
  ALTO = 'ALTO',
  CRITICO = 'CRITICO'
}

export enum NotifTipo {
  ASIGNACION_TICKET = 'ASIGNACION_TICKET',
  CAMBIO_ESTADO = 'CAMBI0_ESTADO',
  VENCIMIENTO = 'VENCIMIENTO',
  RECORDATORIO = 'RECORDATORIO',
  OTRO = 'OTRO'
}

export enum NotifPrioridad {
  BAJA = 'BAJA',
  MEDIA = 'MEDIA',
  ALTA = 'ALTA'
}

export enum ParametroTipo {
  TEXTO = 'TEXTO',
  NUMERO = 'NUMERO',
  BOOLEAN = 'BOOLEAN',
  JSON = 'JSON'
}

export enum ParametroSistema {
  MODO_MANTENIMIENTO = 'MODO_MANTENIMIENTO',
  LIMITE_MAX_SUBIDA_MB = 'LIMITE_MAX_SUBIDA_MB',
  EMAIL_SOPORTE = 'EMAIL_SOPORTE',
  URL_SERVICIO_EXTERNO = 'URL_SERVICIO_EXTERNO',
  TIEMPO_SESION_MIN = 'TIEMPO_SESION_MIN',
  HABILITAR_NOTIFICACIONES = 'HABILITAR_NOTIFICACIONES',
  LOG_LEVEL = 'LOG_LEVEL',
  RETENCION_DATOS_DIAS = 'RETENCION_DATOS_DIAS'
}